version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DataLoop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672      # AMQP Protocol (client connections)
      - 15672:15672    # RabbitMQ Management UI (Web Interface)

volumes:
  pgdata:

